Repository lncm/noma, pull requests merged in 2019-08, with the labels that each got.

#31 lnd.py: add tests for and refactor create_wallet()
  noma/lnd.py
  tests/test_lnd.py
Labels: enhancement

#38 Fix small typo in readme build instructions
  README.md
Labels: bug, documentation

#36 Update LND to 0.7.1
  compose/neutrino/docker-compose.yml
Labels: enhancement

#41 Defines configuration of filesystem structure
  noma/config.py
  noma/node.py
Labels: enhancement

#26 LND Connect functionality for the App and Desktop version
  .gitignore
  README.md
  compose/clearnet/docker-compose.yml
  compose/neutrino/docker-compose.yml
  docs/index.rst
  lnd/neutrino/lnd.conf
  noma/config.py
  noma/lnd.py
  noma/node.py
  noma/noma.py
  setup.py
  tests/test_lnd.py
Labels: documentation, enhancement, help wanted, question
